spring.application.name=enterprise-rag-platform


################################
# Ollama LLM
################################
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=qwen2.5:7b

################################
# Embedding Model
################################
spring.ai.ollama.embedding.options.model=nomic-embed-text

################################
# PostgreSQL Vector Database
################################
spring.datasource.url=jdbc:postgresql://localhost:5432/ragdb
spring.datasource.username=postgres
spring.datasource.password=password

################################
# Vector Store
################################
spring.ai.vectorstore.pgvector.initialize-schema=true