spring.application.name=enterprise-rag-platform


################################
# Ollama LLM
################################
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=qwen2.5:7b

################################
# Embedding Model
################################
spring.ai.ollama.embedding.options.model=nomic-embed-text

################################
# PostgreSQL Vector Database
################################
spring.datasource.url=jdbc:postgresql://localhost:5432/ragdb
spring.datasource.username=raguser
spring.datasource.password=ragpassword
spring.datasource.driver-class-name=org.postgresql.Driver
################################
# Vector Store
################################
spring.ai.vectorstore.pgvector.initialize-schema=true

# Logging
logging.level.com.zaxxer.hikari=DEBUG
logging.level.org.springframework.jdbc=DEBUG

# Splitter
rag.chunk.size=500
rag.chunk.overlap=50

# Retrieval
rag.retrieval.top-k=5
rag.retrieval.similarity-threshold=0.50